#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: user
#      username: admin
#      password: admin
#      authentication-database: admin
spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/basic_authorization_app?authSource=admin